# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/opt/PHP-CPP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/opt/PHP-CPP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/opt/PHP-CPP/CMakeFiles /home/ubuntu/opt/PHP-CPP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/opt/PHP-CPP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named phpcpp

# Build rule for target.
phpcpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 phpcpp
.PHONY : phpcpp

# fast build rule for target.
phpcpp/fast:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/build
.PHONY : phpcpp/fast

#=============================================================================
# Target rules for targets named phpcpp-common

# Build rule for target.
phpcpp-common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 phpcpp-common
.PHONY : phpcpp-common

# fast build rule for target.
phpcpp-common/fast:
	$(MAKE) -f CMakeFiles/phpcpp-common.dir/build.make CMakeFiles/phpcpp-common.dir/build
.PHONY : phpcpp-common/fast

common/modifiers.o: common/modifiers.cpp.o

.PHONY : common/modifiers.o

# target to build an object file
common/modifiers.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp-common.dir/build.make CMakeFiles/phpcpp-common.dir/common/modifiers.cpp.o
.PHONY : common/modifiers.cpp.o

common/modifiers.i: common/modifiers.cpp.i

.PHONY : common/modifiers.i

# target to preprocess a source file
common/modifiers.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp-common.dir/build.make CMakeFiles/phpcpp-common.dir/common/modifiers.cpp.i
.PHONY : common/modifiers.cpp.i

common/modifiers.s: common/modifiers.cpp.s

.PHONY : common/modifiers.s

# target to generate assembly for a file
common/modifiers.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp-common.dir/build.make CMakeFiles/phpcpp-common.dir/common/modifiers.cpp.s
.PHONY : common/modifiers.cpp.s

common/streambuf.o: common/streambuf.cpp.o

.PHONY : common/streambuf.o

# target to build an object file
common/streambuf.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp-common.dir/build.make CMakeFiles/phpcpp-common.dir/common/streambuf.cpp.o
.PHONY : common/streambuf.cpp.o

common/streambuf.i: common/streambuf.cpp.i

.PHONY : common/streambuf.i

# target to preprocess a source file
common/streambuf.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp-common.dir/build.make CMakeFiles/phpcpp-common.dir/common/streambuf.cpp.i
.PHONY : common/streambuf.cpp.i

common/streambuf.s: common/streambuf.cpp.s

.PHONY : common/streambuf.s

# target to generate assembly for a file
common/streambuf.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp-common.dir/build.make CMakeFiles/phpcpp-common.dir/common/streambuf.cpp.s
.PHONY : common/streambuf.cpp.s

zend/base.o: zend/base.cpp.o

.PHONY : zend/base.o

# target to build an object file
zend/base.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/base.cpp.o
.PHONY : zend/base.cpp.o

zend/base.i: zend/base.cpp.i

.PHONY : zend/base.i

# target to preprocess a source file
zend/base.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/base.cpp.i
.PHONY : zend/base.cpp.i

zend/base.s: zend/base.cpp.s

.PHONY : zend/base.s

# target to generate assembly for a file
zend/base.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/base.cpp.s
.PHONY : zend/base.cpp.s

zend/callable.o: zend/callable.cpp.o

.PHONY : zend/callable.o

# target to build an object file
zend/callable.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/callable.cpp.o
.PHONY : zend/callable.cpp.o

zend/callable.i: zend/callable.cpp.i

.PHONY : zend/callable.i

# target to preprocess a source file
zend/callable.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/callable.cpp.i
.PHONY : zend/callable.cpp.i

zend/callable.s: zend/callable.cpp.s

.PHONY : zend/callable.s

# target to generate assembly for a file
zend/callable.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/callable.cpp.s
.PHONY : zend/callable.cpp.s

zend/classbase.o: zend/classbase.cpp.o

.PHONY : zend/classbase.o

# target to build an object file
zend/classbase.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/classbase.cpp.o
.PHONY : zend/classbase.cpp.o

zend/classbase.i: zend/classbase.cpp.i

.PHONY : zend/classbase.i

# target to preprocess a source file
zend/classbase.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/classbase.cpp.i
.PHONY : zend/classbase.cpp.i

zend/classbase.s: zend/classbase.cpp.s

.PHONY : zend/classbase.s

# target to generate assembly for a file
zend/classbase.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/classbase.cpp.s
.PHONY : zend/classbase.cpp.s

zend/classimpl.o: zend/classimpl.cpp.o

.PHONY : zend/classimpl.o

# target to build an object file
zend/classimpl.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/classimpl.cpp.o
.PHONY : zend/classimpl.cpp.o

zend/classimpl.i: zend/classimpl.cpp.i

.PHONY : zend/classimpl.i

# target to preprocess a source file
zend/classimpl.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/classimpl.cpp.i
.PHONY : zend/classimpl.cpp.i

zend/classimpl.s: zend/classimpl.cpp.s

.PHONY : zend/classimpl.s

# target to generate assembly for a file
zend/classimpl.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/classimpl.cpp.s
.PHONY : zend/classimpl.cpp.s

zend/constant.o: zend/constant.cpp.o

.PHONY : zend/constant.o

# target to build an object file
zend/constant.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/constant.cpp.o
.PHONY : zend/constant.cpp.o

zend/constant.i: zend/constant.cpp.i

.PHONY : zend/constant.i

# target to preprocess a source file
zend/constant.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/constant.cpp.i
.PHONY : zend/constant.cpp.i

zend/constant.s: zend/constant.cpp.s

.PHONY : zend/constant.s

# target to generate assembly for a file
zend/constant.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/constant.cpp.s
.PHONY : zend/constant.cpp.s

zend/constantfuncs.o: zend/constantfuncs.cpp.o

.PHONY : zend/constantfuncs.o

# target to build an object file
zend/constantfuncs.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/constantfuncs.cpp.o
.PHONY : zend/constantfuncs.cpp.o

zend/constantfuncs.i: zend/constantfuncs.cpp.i

.PHONY : zend/constantfuncs.i

# target to preprocess a source file
zend/constantfuncs.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/constantfuncs.cpp.i
.PHONY : zend/constantfuncs.cpp.i

zend/constantfuncs.s: zend/constantfuncs.cpp.s

.PHONY : zend/constantfuncs.s

# target to generate assembly for a file
zend/constantfuncs.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/constantfuncs.cpp.s
.PHONY : zend/constantfuncs.cpp.s

zend/eval.o: zend/eval.cpp.o

.PHONY : zend/eval.o

# target to build an object file
zend/eval.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/eval.cpp.o
.PHONY : zend/eval.cpp.o

zend/eval.i: zend/eval.cpp.i

.PHONY : zend/eval.i

# target to preprocess a source file
zend/eval.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/eval.cpp.i
.PHONY : zend/eval.cpp.i

zend/eval.s: zend/eval.cpp.s

.PHONY : zend/eval.s

# target to generate assembly for a file
zend/eval.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/eval.cpp.s
.PHONY : zend/eval.cpp.s

zend/exception_handler.o: zend/exception_handler.cpp.o

.PHONY : zend/exception_handler.o

# target to build an object file
zend/exception_handler.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/exception_handler.cpp.o
.PHONY : zend/exception_handler.cpp.o

zend/exception_handler.i: zend/exception_handler.cpp.i

.PHONY : zend/exception_handler.i

# target to preprocess a source file
zend/exception_handler.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/exception_handler.cpp.i
.PHONY : zend/exception_handler.cpp.i

zend/exception_handler.s: zend/exception_handler.cpp.s

.PHONY : zend/exception_handler.s

# target to generate assembly for a file
zend/exception_handler.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/exception_handler.cpp.s
.PHONY : zend/exception_handler.cpp.s

zend/exists.o: zend/exists.cpp.o

.PHONY : zend/exists.o

# target to build an object file
zend/exists.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/exists.cpp.o
.PHONY : zend/exists.cpp.o

zend/exists.i: zend/exists.cpp.i

.PHONY : zend/exists.i

# target to preprocess a source file
zend/exists.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/exists.cpp.i
.PHONY : zend/exists.cpp.i

zend/exists.s: zend/exists.cpp.s

.PHONY : zend/exists.s

# target to generate assembly for a file
zend/exists.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/exists.cpp.s
.PHONY : zend/exists.cpp.s

zend/extension.o: zend/extension.cpp.o

.PHONY : zend/extension.o

# target to build an object file
zend/extension.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/extension.cpp.o
.PHONY : zend/extension.cpp.o

zend/extension.i: zend/extension.cpp.i

.PHONY : zend/extension.i

# target to preprocess a source file
zend/extension.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/extension.cpp.i
.PHONY : zend/extension.cpp.i

zend/extension.s: zend/extension.cpp.s

.PHONY : zend/extension.s

# target to generate assembly for a file
zend/extension.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/extension.cpp.s
.PHONY : zend/extension.cpp.s

zend/extensionimpl.o: zend/extensionimpl.cpp.o

.PHONY : zend/extensionimpl.o

# target to build an object file
zend/extensionimpl.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/extensionimpl.cpp.o
.PHONY : zend/extensionimpl.cpp.o

zend/extensionimpl.i: zend/extensionimpl.cpp.i

.PHONY : zend/extensionimpl.i

# target to preprocess a source file
zend/extensionimpl.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/extensionimpl.cpp.i
.PHONY : zend/extensionimpl.cpp.i

zend/extensionimpl.s: zend/extensionimpl.cpp.s

.PHONY : zend/extensionimpl.s

# target to generate assembly for a file
zend/extensionimpl.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/extensionimpl.cpp.s
.PHONY : zend/extensionimpl.cpp.s

zend/fatalerror.o: zend/fatalerror.cpp.o

.PHONY : zend/fatalerror.o

# target to build an object file
zend/fatalerror.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/fatalerror.cpp.o
.PHONY : zend/fatalerror.cpp.o

zend/fatalerror.i: zend/fatalerror.cpp.i

.PHONY : zend/fatalerror.i

# target to preprocess a source file
zend/fatalerror.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/fatalerror.cpp.i
.PHONY : zend/fatalerror.cpp.i

zend/fatalerror.s: zend/fatalerror.cpp.s

.PHONY : zend/fatalerror.s

# target to generate assembly for a file
zend/fatalerror.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/fatalerror.cpp.s
.PHONY : zend/fatalerror.cpp.s

zend/file.o: zend/file.cpp.o

.PHONY : zend/file.o

# target to build an object file
zend/file.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/file.cpp.o
.PHONY : zend/file.cpp.o

zend/file.i: zend/file.cpp.i

.PHONY : zend/file.i

# target to preprocess a source file
zend/file.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/file.cpp.i
.PHONY : zend/file.cpp.i

zend/file.s: zend/file.cpp.s

.PHONY : zend/file.s

# target to generate assembly for a file
zend/file.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/file.cpp.s
.PHONY : zend/file.cpp.s

zend/function.o: zend/function.cpp.o

.PHONY : zend/function.o

# target to build an object file
zend/function.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/function.cpp.o
.PHONY : zend/function.cpp.o

zend/function.i: zend/function.cpp.i

.PHONY : zend/function.i

# target to preprocess a source file
zend/function.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/function.cpp.i
.PHONY : zend/function.cpp.i

zend/function.s: zend/function.cpp.s

.PHONY : zend/function.s

# target to generate assembly for a file
zend/function.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/function.cpp.s
.PHONY : zend/function.cpp.s

zend/functor.o: zend/functor.cpp.o

.PHONY : zend/functor.o

# target to build an object file
zend/functor.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/functor.cpp.o
.PHONY : zend/functor.cpp.o

zend/functor.i: zend/functor.cpp.i

.PHONY : zend/functor.i

# target to preprocess a source file
zend/functor.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/functor.cpp.i
.PHONY : zend/functor.cpp.i

zend/functor.s: zend/functor.cpp.s

.PHONY : zend/functor.s

# target to generate assembly for a file
zend/functor.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/functor.cpp.s
.PHONY : zend/functor.cpp.s

zend/global.o: zend/global.cpp.o

.PHONY : zend/global.o

# target to build an object file
zend/global.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/global.cpp.o
.PHONY : zend/global.cpp.o

zend/global.i: zend/global.cpp.i

.PHONY : zend/global.i

# target to preprocess a source file
zend/global.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/global.cpp.i
.PHONY : zend/global.cpp.i

zend/global.s: zend/global.cpp.s

.PHONY : zend/global.s

# target to generate assembly for a file
zend/global.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/global.cpp.s
.PHONY : zend/global.cpp.s

zend/globals.o: zend/globals.cpp.o

.PHONY : zend/globals.o

# target to build an object file
zend/globals.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/globals.cpp.o
.PHONY : zend/globals.cpp.o

zend/globals.i: zend/globals.cpp.i

.PHONY : zend/globals.i

# target to preprocess a source file
zend/globals.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/globals.cpp.i
.PHONY : zend/globals.cpp.i

zend/globals.s: zend/globals.cpp.s

.PHONY : zend/globals.s

# target to generate assembly for a file
zend/globals.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/globals.cpp.s
.PHONY : zend/globals.cpp.s

zend/hashmember.o: zend/hashmember.cpp.o

.PHONY : zend/hashmember.o

# target to build an object file
zend/hashmember.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/hashmember.cpp.o
.PHONY : zend/hashmember.cpp.o

zend/hashmember.i: zend/hashmember.cpp.i

.PHONY : zend/hashmember.i

# target to preprocess a source file
zend/hashmember.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/hashmember.cpp.i
.PHONY : zend/hashmember.cpp.i

zend/hashmember.s: zend/hashmember.cpp.s

.PHONY : zend/hashmember.s

# target to generate assembly for a file
zend/hashmember.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/hashmember.cpp.s
.PHONY : zend/hashmember.cpp.s

zend/ini.o: zend/ini.cpp.o

.PHONY : zend/ini.o

# target to build an object file
zend/ini.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/ini.cpp.o
.PHONY : zend/ini.cpp.o

zend/ini.i: zend/ini.cpp.i

.PHONY : zend/ini.i

# target to preprocess a source file
zend/ini.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/ini.cpp.i
.PHONY : zend/ini.cpp.i

zend/ini.s: zend/ini.cpp.s

.PHONY : zend/ini.s

# target to generate assembly for a file
zend/ini.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/ini.cpp.s
.PHONY : zend/ini.cpp.s

zend/inivalue.o: zend/inivalue.cpp.o

.PHONY : zend/inivalue.o

# target to build an object file
zend/inivalue.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/inivalue.cpp.o
.PHONY : zend/inivalue.cpp.o

zend/inivalue.i: zend/inivalue.cpp.i

.PHONY : zend/inivalue.i

# target to preprocess a source file
zend/inivalue.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/inivalue.cpp.i
.PHONY : zend/inivalue.cpp.i

zend/inivalue.s: zend/inivalue.cpp.s

.PHONY : zend/inivalue.s

# target to generate assembly for a file
zend/inivalue.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/inivalue.cpp.s
.PHONY : zend/inivalue.cpp.s

zend/iteratorimpl.o: zend/iteratorimpl.cpp.o

.PHONY : zend/iteratorimpl.o

# target to build an object file
zend/iteratorimpl.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/iteratorimpl.cpp.o
.PHONY : zend/iteratorimpl.cpp.o

zend/iteratorimpl.i: zend/iteratorimpl.cpp.i

.PHONY : zend/iteratorimpl.i

# target to preprocess a source file
zend/iteratorimpl.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/iteratorimpl.cpp.i
.PHONY : zend/iteratorimpl.cpp.i

zend/iteratorimpl.s: zend/iteratorimpl.cpp.s

.PHONY : zend/iteratorimpl.s

# target to generate assembly for a file
zend/iteratorimpl.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/iteratorimpl.cpp.s
.PHONY : zend/iteratorimpl.cpp.s

zend/members.o: zend/members.cpp.o

.PHONY : zend/members.o

# target to build an object file
zend/members.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/members.cpp.o
.PHONY : zend/members.cpp.o

zend/members.i: zend/members.cpp.i

.PHONY : zend/members.i

# target to preprocess a source file
zend/members.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/members.cpp.i
.PHONY : zend/members.cpp.i

zend/members.s: zend/members.cpp.s

.PHONY : zend/members.s

# target to generate assembly for a file
zend/members.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/members.cpp.s
.PHONY : zend/members.cpp.s

zend/module.o: zend/module.cpp.o

.PHONY : zend/module.o

# target to build an object file
zend/module.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/module.cpp.o
.PHONY : zend/module.cpp.o

zend/module.i: zend/module.cpp.i

.PHONY : zend/module.i

# target to preprocess a source file
zend/module.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/module.cpp.i
.PHONY : zend/module.cpp.i

zend/module.s: zend/module.cpp.s

.PHONY : zend/module.s

# target to generate assembly for a file
zend/module.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/module.cpp.s
.PHONY : zend/module.cpp.s

zend/namespace.o: zend/namespace.cpp.o

.PHONY : zend/namespace.o

# target to build an object file
zend/namespace.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/namespace.cpp.o
.PHONY : zend/namespace.cpp.o

zend/namespace.i: zend/namespace.cpp.i

.PHONY : zend/namespace.i

# target to preprocess a source file
zend/namespace.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/namespace.cpp.i
.PHONY : zend/namespace.cpp.i

zend/namespace.s: zend/namespace.cpp.s

.PHONY : zend/namespace.s

# target to generate assembly for a file
zend/namespace.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/namespace.cpp.s
.PHONY : zend/namespace.cpp.s

zend/object.o: zend/object.cpp.o

.PHONY : zend/object.o

# target to build an object file
zend/object.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/object.cpp.o
.PHONY : zend/object.cpp.o

zend/object.i: zend/object.cpp.i

.PHONY : zend/object.i

# target to preprocess a source file
zend/object.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/object.cpp.i
.PHONY : zend/object.cpp.i

zend/object.s: zend/object.cpp.s

.PHONY : zend/object.s

# target to generate assembly for a file
zend/object.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/object.cpp.s
.PHONY : zend/object.cpp.s

zend/sapi.o: zend/sapi.cpp.o

.PHONY : zend/sapi.o

# target to build an object file
zend/sapi.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/sapi.cpp.o
.PHONY : zend/sapi.cpp.o

zend/sapi.i: zend/sapi.cpp.i

.PHONY : zend/sapi.i

# target to preprocess a source file
zend/sapi.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/sapi.cpp.i
.PHONY : zend/sapi.cpp.i

zend/sapi.s: zend/sapi.cpp.s

.PHONY : zend/sapi.s

# target to generate assembly for a file
zend/sapi.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/sapi.cpp.s
.PHONY : zend/sapi.cpp.s

zend/script.o: zend/script.cpp.o

.PHONY : zend/script.o

# target to build an object file
zend/script.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/script.cpp.o
.PHONY : zend/script.cpp.o

zend/script.i: zend/script.cpp.i

.PHONY : zend/script.i

# target to preprocess a source file
zend/script.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/script.cpp.i
.PHONY : zend/script.cpp.i

zend/script.s: zend/script.cpp.s

.PHONY : zend/script.s

# target to generate assembly for a file
zend/script.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/script.cpp.s
.PHONY : zend/script.cpp.s

zend/streambuf.o: zend/streambuf.cpp.o

.PHONY : zend/streambuf.o

# target to build an object file
zend/streambuf.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/streambuf.cpp.o
.PHONY : zend/streambuf.cpp.o

zend/streambuf.i: zend/streambuf.cpp.i

.PHONY : zend/streambuf.i

# target to preprocess a source file
zend/streambuf.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/streambuf.cpp.i
.PHONY : zend/streambuf.cpp.i

zend/streambuf.s: zend/streambuf.cpp.s

.PHONY : zend/streambuf.s

# target to generate assembly for a file
zend/streambuf.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/streambuf.cpp.s
.PHONY : zend/streambuf.cpp.s

zend/streams.o: zend/streams.cpp.o

.PHONY : zend/streams.o

# target to build an object file
zend/streams.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/streams.cpp.o
.PHONY : zend/streams.cpp.o

zend/streams.i: zend/streams.cpp.i

.PHONY : zend/streams.i

# target to preprocess a source file
zend/streams.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/streams.cpp.i
.PHONY : zend/streams.cpp.i

zend/streams.s: zend/streams.cpp.s

.PHONY : zend/streams.s

# target to generate assembly for a file
zend/streams.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/streams.cpp.s
.PHONY : zend/streams.cpp.s

zend/super.o: zend/super.cpp.o

.PHONY : zend/super.o

# target to build an object file
zend/super.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/super.cpp.o
.PHONY : zend/super.cpp.o

zend/super.i: zend/super.cpp.i

.PHONY : zend/super.i

# target to preprocess a source file
zend/super.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/super.cpp.i
.PHONY : zend/super.cpp.i

zend/super.s: zend/super.cpp.s

.PHONY : zend/super.s

# target to generate assembly for a file
zend/super.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/super.cpp.s
.PHONY : zend/super.cpp.s

zend/value.o: zend/value.cpp.o

.PHONY : zend/value.o

# target to build an object file
zend/value.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/value.cpp.o
.PHONY : zend/value.cpp.o

zend/value.i: zend/value.cpp.i

.PHONY : zend/value.i

# target to preprocess a source file
zend/value.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/value.cpp.i
.PHONY : zend/value.cpp.i

zend/value.s: zend/value.cpp.s

.PHONY : zend/value.s

# target to generate assembly for a file
zend/value.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/value.cpp.s
.PHONY : zend/value.cpp.s

zend/valueiterator.o: zend/valueiterator.cpp.o

.PHONY : zend/valueiterator.o

# target to build an object file
zend/valueiterator.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/valueiterator.cpp.o
.PHONY : zend/valueiterator.cpp.o

zend/valueiterator.i: zend/valueiterator.cpp.i

.PHONY : zend/valueiterator.i

# target to preprocess a source file
zend/valueiterator.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/valueiterator.cpp.i
.PHONY : zend/valueiterator.cpp.i

zend/valueiterator.s: zend/valueiterator.cpp.s

.PHONY : zend/valueiterator.s

# target to generate assembly for a file
zend/valueiterator.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/valueiterator.cpp.s
.PHONY : zend/valueiterator.cpp.s

zend/zendcallable.o: zend/zendcallable.cpp.o

.PHONY : zend/zendcallable.o

# target to build an object file
zend/zendcallable.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/zendcallable.cpp.o
.PHONY : zend/zendcallable.cpp.o

zend/zendcallable.i: zend/zendcallable.cpp.i

.PHONY : zend/zendcallable.i

# target to preprocess a source file
zend/zendcallable.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/zendcallable.cpp.i
.PHONY : zend/zendcallable.cpp.i

zend/zendcallable.s: zend/zendcallable.cpp.s

.PHONY : zend/zendcallable.s

# target to generate assembly for a file
zend/zendcallable.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/zendcallable.cpp.s
.PHONY : zend/zendcallable.cpp.s

zend/zval.o: zend/zval.cpp.o

.PHONY : zend/zval.o

# target to build an object file
zend/zval.cpp.o:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/zval.cpp.o
.PHONY : zend/zval.cpp.o

zend/zval.i: zend/zval.cpp.i

.PHONY : zend/zval.i

# target to preprocess a source file
zend/zval.cpp.i:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/zval.cpp.i
.PHONY : zend/zval.cpp.i

zend/zval.s: zend/zval.cpp.s

.PHONY : zend/zval.s

# target to generate assembly for a file
zend/zval.cpp.s:
	$(MAKE) -f CMakeFiles/phpcpp.dir/build.make CMakeFiles/phpcpp.dir/zend/zval.cpp.s
.PHONY : zend/zval.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... phpcpp"
	@echo "... phpcpp-common"
	@echo "... common/modifiers.o"
	@echo "... common/modifiers.i"
	@echo "... common/modifiers.s"
	@echo "... common/streambuf.o"
	@echo "... common/streambuf.i"
	@echo "... common/streambuf.s"
	@echo "... zend/base.o"
	@echo "... zend/base.i"
	@echo "... zend/base.s"
	@echo "... zend/callable.o"
	@echo "... zend/callable.i"
	@echo "... zend/callable.s"
	@echo "... zend/classbase.o"
	@echo "... zend/classbase.i"
	@echo "... zend/classbase.s"
	@echo "... zend/classimpl.o"
	@echo "... zend/classimpl.i"
	@echo "... zend/classimpl.s"
	@echo "... zend/constant.o"
	@echo "... zend/constant.i"
	@echo "... zend/constant.s"
	@echo "... zend/constantfuncs.o"
	@echo "... zend/constantfuncs.i"
	@echo "... zend/constantfuncs.s"
	@echo "... zend/eval.o"
	@echo "... zend/eval.i"
	@echo "... zend/eval.s"
	@echo "... zend/exception_handler.o"
	@echo "... zend/exception_handler.i"
	@echo "... zend/exception_handler.s"
	@echo "... zend/exists.o"
	@echo "... zend/exists.i"
	@echo "... zend/exists.s"
	@echo "... zend/extension.o"
	@echo "... zend/extension.i"
	@echo "... zend/extension.s"
	@echo "... zend/extensionimpl.o"
	@echo "... zend/extensionimpl.i"
	@echo "... zend/extensionimpl.s"
	@echo "... zend/fatalerror.o"
	@echo "... zend/fatalerror.i"
	@echo "... zend/fatalerror.s"
	@echo "... zend/file.o"
	@echo "... zend/file.i"
	@echo "... zend/file.s"
	@echo "... zend/function.o"
	@echo "... zend/function.i"
	@echo "... zend/function.s"
	@echo "... zend/functor.o"
	@echo "... zend/functor.i"
	@echo "... zend/functor.s"
	@echo "... zend/global.o"
	@echo "... zend/global.i"
	@echo "... zend/global.s"
	@echo "... zend/globals.o"
	@echo "... zend/globals.i"
	@echo "... zend/globals.s"
	@echo "... zend/hashmember.o"
	@echo "... zend/hashmember.i"
	@echo "... zend/hashmember.s"
	@echo "... zend/ini.o"
	@echo "... zend/ini.i"
	@echo "... zend/ini.s"
	@echo "... zend/inivalue.o"
	@echo "... zend/inivalue.i"
	@echo "... zend/inivalue.s"
	@echo "... zend/iteratorimpl.o"
	@echo "... zend/iteratorimpl.i"
	@echo "... zend/iteratorimpl.s"
	@echo "... zend/members.o"
	@echo "... zend/members.i"
	@echo "... zend/members.s"
	@echo "... zend/module.o"
	@echo "... zend/module.i"
	@echo "... zend/module.s"
	@echo "... zend/namespace.o"
	@echo "... zend/namespace.i"
	@echo "... zend/namespace.s"
	@echo "... zend/object.o"
	@echo "... zend/object.i"
	@echo "... zend/object.s"
	@echo "... zend/sapi.o"
	@echo "... zend/sapi.i"
	@echo "... zend/sapi.s"
	@echo "... zend/script.o"
	@echo "... zend/script.i"
	@echo "... zend/script.s"
	@echo "... zend/streambuf.o"
	@echo "... zend/streambuf.i"
	@echo "... zend/streambuf.s"
	@echo "... zend/streams.o"
	@echo "... zend/streams.i"
	@echo "... zend/streams.s"
	@echo "... zend/super.o"
	@echo "... zend/super.i"
	@echo "... zend/super.s"
	@echo "... zend/value.o"
	@echo "... zend/value.i"
	@echo "... zend/value.s"
	@echo "... zend/valueiterator.o"
	@echo "... zend/valueiterator.i"
	@echo "... zend/valueiterator.s"
	@echo "... zend/zendcallable.o"
	@echo "... zend/zendcallable.i"
	@echo "... zend/zendcallable.s"
	@echo "... zend/zval.o"
	@echo "... zend/zval.i"
	@echo "... zend/zval.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

